server:
  servlet:
    session:
      tracking-modes: cookie
spring:
  application:
    name: logly
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  messages:
    basename: errors
    encoding: UTF-8
  h2:
    console:
      enabled: true